# project
title: Minimit
description: 
authors: Riccardo Caroli
url: "http://www.minimit.com"

# settings
source: src/docs/
destination: docs/
baseurl: ""
exclude:
  - "*.psd"
  - "*.scss"
  
# Dependencies
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true

# Custom vars