# project
title: Xtend
description: 
authors: Riccardo Caroli
url: "http://www.minimit.com"
version: 0.0.6
twitter: "https://twitter.com/beaver82minimit"
google: "https://plus.google.com/+Minimit"

# settings
source: "src/docs/"
destination: "docs/"
baseurl: "/"
exclude:
  - "*.psd"
  - "*.scss"
port: 4000
host: 192.168.1.183
  
# collections
collections:
  docs:
    output: true
    permalink: '/:collection/:path/'
    links:
      github: "https://github.com/minimit/minimit"
      download: "https://github.com/minimit/minimit/archive/master.zip"
defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: sidebar
      